# Generated by Django 6.0.2 on 2026-04-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_email_2fa_and_otp_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('responsable_stock', 'Responsable Stock'), ('responsable_appro', 'Responsable Approvisionnement'), ('responsable_production', 'Responsable Production'), ('responsable_facturation', 'Responsable Facturation'), ('responsable_commandes', 'Responsable Commandes'), ('agent_stock', 'Agent Stock'), ('agent_production', 'Agent Production'), ('employe', 'Employé')], default='employe', max_length=30, verbose_name='role'),
        ),
    ]
