# Generated by Django 6.0.2 on 2026-04-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotpchallenge',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], default='email', max_length=20),
        ),
    ]
