# Generated by Django 6.0.2 on 2026-04-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='check_condition',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
