# Generated by Django 6.0.2 on 2026-04-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_check_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Alerte en pause - pas de notifications'),
        ),
    ]
