# Generated by Django 4.2.7 on 2026-04-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alert_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='custom_body',
            field=models.TextField(blank=True, help_text="Corps d'email personnalisé", null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='custom_subject',
            field=models.CharField(blank=True, help_text="Sujet d'email personnalisé", max_length=255, null=True),
        ),
    ]
