# Generated by Django 4.2.7 on 2026-04-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alert_custom_body_alert_custom_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notif_type',
            field=models.CharField(blank=True, help_text='Type de notification', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='recipient_role',
            field=models.CharField(blank=True, help_text='Rôle des destinataires', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='recurrence',
            field=models.CharField(blank=True, help_text='Récurrence', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='snooze_hours',
            field=models.IntegerField(default=0, help_text="Heures de délai pour reporter l'alerte"),
        ),
        migrations.AlterField(
            model_name='alert',
            name='notification_channels',
            field=models.JSONField(blank=True, default=list, help_text='Liste des canaux de notification'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='recipients',
            field=models.JSONField(blank=True, default=list, help_text='Liste des destinataires'),
        ),
    ]
