# Generated by Django 4.2.16 on 2026-04-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channels',
            field=models.JSONField(blank=True, default=list, help_text="Liste des canaux choisis, ex: ['email', 'inapp']"),
        ),
    ]
