# Generated by Django 5.x on ...

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannelpreference',
            name='telegram_enabled',
            field=models.BooleanField(default=True),
        ),
    ]

