# Generated by Django 4.2.7 on 2026-04-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='delivery_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
