# Generated by Django 6.0.2 on 2026-04-15 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0002_supplier_delivery_time_supplier_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='anciennete',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='capacite_production',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='commentaires',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='conditions_paiement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='delai_livraison',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='garantie_sav',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='identifiant_fiscal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='minimum_commande',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='note_globale',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='prix_unitaire',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='references_clients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='registre_commerce',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='remise',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='secteur',
            field=models.CharField(blank=True, choices=[('Informatique', 'Informatique'), ('Matériel', 'Matériel'), ('Services', 'Services'), ('Électronique', 'Électronique'), ('Industriel', 'Industriel'), ('Textile', 'Textile'), ('Alimentaire', 'Alimentaire'), ('Automobile', 'Automobile'), ('BTP', 'BTP'), ('Autre', 'Autre')], max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='zone_couverture',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
