# Generated by Django 6.0.2 on 2026-04-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0003_supplier_anciennete_supplier_capacite_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='secteur',
            field=models.CharField(blank=True, choices=[('matiere_premiere', 'Matière Première'), ('matiere_consommable', 'Matière Consommable'), ('matiere_emballage', 'Matière Emballage'), ('matiere_chimique', 'Matière Chimique'), ('matiere_dangereuse', 'Matière Dangereuse'), ('fourniture_bureau', 'Fournitures Bureau')], max_length=50),
        ),
    ]
