# Generated by Django 4.2.7 on 2026-05-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0004_alter_supplier_secteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='famille',
            field=models.CharField(blank=True, choices=[('matiere_premiere', 'Matière Première'), ('matiere_consommable', 'Matière Consommable'), ('matiere_emballage', 'Matière Emballage'), ('matiere_chimique', 'Matière Chimique'), ('matiere_dangereuse', 'Matière Dangereuse'), ('fourniture_bureau', 'Fournitures Bureau')], max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='secteur',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
