# Generated by Django 4.2.7 on 2026-05-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_movements', '0004_stockmovement_recipient_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={},
        ),
    ]
